### ISSUE TITLE
Spaces between words

### ISSUE THREAD

**Issue by emecs** [jhukdev/preact-parser#1]
After conversion spaces between words are lost.

Example:
`<p><strong>How</strong> <em>are</em> you?</p>`
Expected output: "**How** *are* you?"

Is converted to:
`<p><strong>How</strong><em>are</em>you?</p>`
Actual output: "**How***are*you?"

**Comment by jahilldev** [comment]
@emecs Hi there,

I've just taken a look, and confirmed this is an issue.

I've opened a PR here: https://github.com/jhukdev/preact-parser/pull/2 that now preserves individual spaces between words

I'll merge and publish shortly

Thanks for helping out 👍

**Comment by jahilldev** [comment]
@emecs Ok merged & published.

https://github.com/jhukdev/preact-parser/releases/tag/1.2.0

Let me know how you get on, good or bad 👍

**Comment by emecs** [comment]
@jhukdev Works great, thank you.
Keep up the good work!

**Comment by jahilldev** [comment]
@emecs Great! One other thing to mention; I've just released v1.3.0 which has a breaking change, we're now exporting `parse` instead of `html`, as it makes more sense as an API:

https://github.com/jhukdev/preact-parser/releases/tag/1.3.0

Thanks again for the heads up on the bug!
